<?php
echo 'Suite2Psr Configuration'.PHP_EOL;
global $vendor;
$vendor = array(
    'include'.DIRECTORY_SEPARATOR.'HTMLPurifier'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'HTTP_WebDAV_Server'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'nusoap'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'pclzip'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'Pear'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'phpmailer'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'reCaptcha'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'tcpdf'.DIRECTORY_SEPARATOR,
    'include'.DIRECTORY_SEPARATOR.'Smarty'.DIRECTORY_SEPARATOR,
    'Zend'.DIRECTORY_SEPARATOR,
    'XTemplate'.DIRECTORY_SEPARATOR,
);
?>